# This is a basic workflow to help you get started with Actions

name: deploy_back

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: deploy_back
    concurrency: 
      group: deploy_back
      cancel-in-progress: true
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: bash deployTokenDobra.sh

